### ISSUE TITLE
Configured so that each channel can use different clients

### ISSUE THREAD

**Issue by sjh836** [DanielLiu1123/httpexchange-spring-boot-starter#33]
This library is really well made.
It is a spring feature that can be easily applied right away.

I have to use both the normal return type and the return type of Reactive Stream through the http interface.
Also, I would like to adjust the timeout dynamically.

Therefore, I hope it works as follows.
I wish each channel could have a separate remote client.

```yaml
http-exchange:
  enabled: true
  refresh:
    enabled: false
  read-timeout: 2000
  connect-timeout: 500
  #client-type: WEB_CLIENT
  channels:
    - base-url: 'https://jsonplaceholder.typicode.com'
      #client-type: REST_CLIENT #here
      #read-timeout: 500
      #connect-timeout: 200
      clients:
        - com.devljh.module.http.*HttpClient
    - base-url: 'https://jsonplaceholder.typicode.com'
      #client-type: WEB_CLIENT #here
      clients:
        - com.devljh.module.http.*ReactiveHttpClient

```

It doesn't work now, and an error occurs because the rest client cannot convert Mono/Flux messages.

**Comment by DanielLiu1123** [comment]
> I have to use both the normal return type and the return type of Reactive Stream through the http interface.

This feature should work fine.

> Also, I would like to adjust the timeout dynamically.

I've also been trying to implement this feature recently. However, it seems that Spring doesn't provide the corresponding API, so this issue is a bit tricky at the moment. If you have any good ideas, please let me know!

> Therefore, I hope it works as follows.
> I wish each channel could have a separate remote client.

As for your request, the issue here is: a client that matches the `com.devljh.module.http.*ReactiveHttpClient` pattern will definitely match the `com.devljh.module.http.*HttpClient` as well, and it will use the first configuration that it hits. Swapping their order should meet your needs.

```yaml
http-exchange:
  channels:
    - base-url: 'https://jsonplaceholder.typicode.com'
      client-type: WEB_CLIENT
      read-timeout: 500
      connect-timeout: 200
      clients:
        - com.devljh.module.http.*ReactiveHttpClient
    - base-url: 'https://jsonplaceholder.typicode.com'
      client-type: REST_CLIENT
      clients:
        - com.devljh.module.http.*HttpClient
```
