### ISSUE TITLE
Support for authentication and mTLS

### ISSUE THREAD

**Issue by yesid-bocanegra** [DanielLiu1123/httpexchange-spring-boot-starter#75]
First of all, Thanks for this project! I haven't actually used it but went through all the documentation and it seems to do what I need, once I have more time will definetely make use of it.

I can see you have support to add headers to the client and it would suffice for api keys and long lived bearer tokens, even for basic auth but it would be nice to have a usr, pwd pair and it calculating the base64. its simple but nice to have in configuration.

It starts to get tricky with OAuth2, it would be awesome to have the configuration to just put in your .wellknow url along with credentials and authentication scheme and generate the code to generate and refresh the tokens. I know this is large and haven't comb through the code to know if it feasible but it would an interesting approach.

Also, using certificate bundles to configure the mutual tls for each client would be useful. I'm not sure if adding the bundle to spring will propagate to the created clients.

**Comment by DanielLiu1123** [comment]
Thank you for your feedback!

**About Basic Auth and OAuth2**:

I don’t plan to provide direct support at the framework level. They might be better handled through code rather than configuration. You can flexibly configure authentication information by naming the channel.

```yaml
# application.yaml
http-exchange:
  base-packages: [ com.example.*.api ]
  channels:
    - name: user
      base-url: http://user
      clients:
        - com.example.user.api.**
    - name: order
      base-url: http://order
      clients:
        - com.example.order.api.**
```

```java
/**
 * Configure for all channels
 */
@Bean
HttpClientCustomizer.RestClientCustomizer restClientCustomizerForAllChannels() {
    return (client, channel) -> {
        var encode = Base64.getEncoder().encode("user:password".getBytes(UTF_8));
        client.defaultHeader(HttpHeaders.AUTHORIZATION, "Bearer " + new String(encode, UTF_8));
    };
}

/**
 * Configure for specific channel
 */
@Bean
HttpClientCustomizer.RestClientCustomizer restClientCustomizerForUserChannel() {
    return (client, channel) -> {
        if (Objects.equals(channel.getName(), "user")) {
            var encode = Base64.getEncoder().encode("user:password".getBytes(UTF_8));
            client.defaultHeader(HttpHeaders.AUTHORIZATION, "Bearer " + new String(encode, UTF_8));
        }
    };
}
```

**About mTLS**:

This feature is great, and it integrates very well with Spring. I will support it, possibly with a configuration like the following:
```yaml
spring:
  ssl:
    bundle:
      pem:
        bundle-01:
          ...
        bundle-02:
          ...
  http:
    client:
      ssl:
        # default bundle for all channels
        bundle: bundle-01
http-exchange:
  base-packages: [ com.example.*.api ]
  channels:
    - name: user
      base-url: http://user
      clients:
        - com.example.user.api.**
    - name: order
      base-url: http://order
      ssl:
        bundle: bundle-02 # specify bundle for order channel
      clients:
        - com.example.order.api.**
```
